### PR TITLE
feat: use new neovim apis, add `:healthcheck`, fix sudo `query_command`

### LINKED ISSUE #33: Use `vim.uv` instead of `vim.loop` if available
`vim.loop` will be removed with1.0 (https://neovim.io/doc/user/deprecated.html#vim.loop), we should use the new `vim.uv` if it isn't `nil` to futureproof the plugin.

### LINKED ISSUE #34: WSL implementation depends on `reg.exe` being on `$PATH`
It's pretty common to have `interop.appendWindowsPath` set to `false` in `/etc/wsl.conf`, to reduce the length of `$PATH`, which in turn improves the performance of lots of WSL/unix tooling. With this set to false, the host system Windows `$PATH` won't be inherited - and `reg.exe` will not be available on `$PATH`.

The documentation should note that `reg.exe` is required to be available on `$PATH` (usually via `/mnt/c/Windows/system32`), or we should offer a way to explicitly set the binary path of `reg.exe` in the plugin options, possibly defaulting to that `/mnt/c` path.

`interop.enabled` also needs to be set to `true`, otherwise WSL will not be able to execute windows binaries.
https://learn.microsoft.com/en-us/windows/wsl/wsl-config#interop-settings

### PR DESCRIPTION
**Pull request by nekowinston**
Uses `vim.uv` over `vim.loop`, `vim.system` over `vim.fn.jobstart`, adds a `:checkhealth` hook with a query_command benchmark, and fixes the `SUDO_USER` query_command. Still preserves fallbacks for jobstart & vim.loop so it will work on older neovim versions.

Also uses `vim.validate` to validate the plugin options and refactors quite a bit; moving the query/interval logic into its own lua module.

It's still a bit of a mess right now but I figured I'd open the PR sooner rather than later.

Fixes #33.
Fixes #34.

### CODE REVIEW

**Comment by nekowinston** [comment]
I still need to check if this works on neovim 0.8 and neovim 0.9, but support for 0.10 should work fine already.

**Comment by sedlund** [comment]
this still seems to broken on master for me on wsl

File: lua/auto-dark-mode/health.lua [hunk 1]
```diff
@@ -0,0 +1,102 @@
...
+		result.max = result.max > v and result.max or v
+		result.min = result.min < v and result.min or v
+		sum = sum + v
+	end
+	result.avg = sum / iterations
+
+	return result
+end
+
+-- support for neovim < 0.9.0
```
Comment (nekowinston) [inline lua/auto-dark-mode/health.lua:52]: We can't actually test neovim 0.8.x with the busted test runner.
It looks like Ubuntu 24.04 and onward now have 0.9 [in their repositories](https://repology.org/project/neovim/versions), so  I'm not sure if supporting 0.8 is even worth it.

Comment (nekowinston) [reply lua/auto-dark-mode/health.lua:52]: I migrated the tests to use [Plenary's busted](https://github.com/nvim-lua/plenary.nvim/blob/master/TESTS_README.md) instead, things should work for earlier versions now.

**Comment by nekowinston** [comment]
I just need a Windows/WSL system to test this on, but should be able to do that this weekend. Aiming to merge it after that.

Sorry for letting this PR sit for a while.
